namespace Bank.Logic;

// do not edit this file

public static class TransactionTypeExtensions
{
    public static bool InidicatesNegativeAmount(this TransactionType type) =>
        type == TransactionType.Withdrawal || type == TransactionType.Fee_Overdraft || type == TransactionType.Fee_Management;

    public static bool InidicatesPositiveAmount(this TransactionType type) =>
        type == TransactionType.Deposit || type == TransactionType.Interest;

    public static bool IndicatesSystemType(this TransactionType type) =>
        type == TransactionType.Fee_Overdraft || type == TransactionType.Fee_Management || type == TransactionType.Interest;
}